variables:
    env:
        description: This is the PROD environment
        default: prod

    bronze_root_path:
        description: This is the Bronze Layer Root Path in PROD environment
        default: /Volumes/prod_oc_dab/prod_bronze/volume_bronze/

    silver_root_path:
        description: This is the Silver Layer Root Path in PROD environment
        default: /Volumes/prod_oc_dab/prod_silver/volume_silver/

    gold_root_path:
        description: This is the Gold Layer Root Path in PROD environment
        default: /Volumes/prod_oc_dab/prod_gold/volume_gold/

    csv_file_format:
        description: This is the CSV File Format
        default: csv