targets:
  dev:
    mode: development
    default: true
    workspace:
      host: "https://dbc-e23f01cd-de6d.cloud.databricks.com/"

    variables:
      include_path: "variables/dev_var.yml"

    presets:
      name_prefix: "(${var.env}_${workspace.current_user.short_name})"