targets:
  dev:
    mode: development
    default: true
    workspace:
      host: "https://dbc-e23f01cd-de6d.cloud.databricks.com/"

    variables:
      include_path: "../variables/dev_var.yml"

    presets:
      name_prefix: "(dev_${workspace.current_user.short_name})"
    
    permissions:
      - user_name: "oindrila.chakraborty88@gmail.com"
        level: CAN_MANAGE
      - user_name: "oindrila.chakraborty88@gmail.com"
        level: CAN_RUN