targets:
  prod:
    mode: production
    default: false
    workspace:
      host: "https://dbc-fabed7ba-6bdf.cloud.databricks.com/"
      root_path: "/prod/${bundle.name}"

    variables:
      include_path: "../variables/prod_var.yml"

    permissions:
      - user_name: "oindrila.chakraborty2988@gmail.com"
        level: CAN_MANAGE
      - user_name: "oindrila.chakraborty2988@gmail.com"
        level: CAN_RUN