targets:
  prod:
    mode: production
    default: false
    workspace:
      host: "https://dbc-fabed7ba-6bdf.cloud.databricks.com/"
      root_path: "/Workspace/Shared/bundles/${bundle.name}"

    permissions:
      - user_name: "oindrila.chakraborty2988@gmail.com"
        level: CAN_MANAGE
      - user_name: "oindrila.chakraborty2988@gmail.com"
        level: CAN_RUN