variables:
    env:
        default: "prod"

    bronze_root_path:
        default: "/Volumes/prod_oc_dab/prod_bronze/volume_bronze/"

    silver_root_path:
        default: "/Volumes/prod_oc_dab/prod_silver/volume_silver/"

    gold_root_path:
        default: "/Volumes/prod_oc_dab/prod_gold/volume_gold/"

    csv_file_format:
        default: "csv"

    instance_policy_id:
        default: "prod-policy-id-efgh"

    instance_pool_id:
        default: "prod-pool-id-5678"

    cluster_node_type:
        default: "Standard_D8s_v5"

    spark_version:
        default: "17.3.x-scala2.12"

    min_worker:
        default: 2

    max_worker:
        default: 16

    serverless_cluster_type:
        default: "PERFORMANCE_OPTIMIZED"

    success_alert_recipient:
        type: list
        default:
            - "miakayuki2011@gmail.com"
            - "soumyajyoti.bagchi@gmail.com"

    fail_alert_recipient:
        type: list
        default:
            - "oindrila.chakraborty@genpact.com"
            - "soumyajyoti.bagchi@capgemini.com"

    paused_status:
        default: "UNPAUSED"