# Workflow name shown in the GitHub Actions Dashboard
name: Deploy to Dev Databricks

# Tells GitHub when to execute this Workflow
on:
  # Ensures that this Deployment Workflow only triggers when a successful PUSH is made directly to the 'dev' branch
  push:
    branches:
      - dev

# This overarching section groups all the Tasks in this Workflow
jobs:
  # Identifier for this specific job
  deploy-to-dev-databricks:
    # Tells GitHub to run this Job on a Linux Virtual Machine
    runs-on: ubuntu-latest

    # List of sequential steps to execute
    steps:
      # Step 1
      - name: Checkout Code
        # A built-in GitHub Action that pulls the repository's code into the Linux VM i.e., runner, so that this Workflow can acces the Notebooks and Configuration Files
        uses: actions/checkout@v4
        
      # Step 2
      - name: Set Up Databricks CLI
        # Installs the Databricks CLI natively on the Linux VM i.e., runner, to execute Bundles commands
        # This uses the stable "main" branch of the action and downloads the latest Databricks CLI
        uses: databricks/setup-cli@main
        # To download a particular version of Databricks CLI executables, the version, such as "1.2.1", is configured as a parameter under the "with" block 
        with:
          version: 1.2.1

      # Step 3
      - name: Inject Configuration to DAB Overrides
        run: |
          # Create the exact override directory DAB expects for that target
          mkdir -p .databricks/bundle/dev
          
          # Copy your JSON into the variable-overrides file
          cp variables/dev_var.json .databricks/bundle/dev/variable-overrides.json
        
      # Step 4
      - name: Validate Databricks Asset Bundles
        # Executes a Terminal command, i.e., "databricks bundle validate", which reads the "databricks.yml" Configuration file and validates the Databricks Asset Bundles (DABs) to check the syntax, structure, and references of the configuration files before deployment.
        # It is a local dry-run command that ensures that the project is error-free, and, prevents failed deployments to the target Databricks Workspace, i.e., dev
        # This forces the runner to jump into the root folder before executing the validate command
        env:
        # URL to the target Databricks Workspace
          DATABRICKS_HOST: ${{secrets.DEV_DBR_HOST}}
          # Secure Authentication Token that grants the Databricks CLI permision to make changes in the target Databricks Workspace
          DATABRICKS_TOKEN: ${{secrets.DEV_DBR_TOKEN}}
        run: |
          databricks bundle validate -t dev

      # Step 5
      - name: Deploy Databricks Asset Bundles
        # Defines the Environment Variables for Shell to utilize
        env:
          # URL to the target Databricks Workspace
          DATABRICKS_HOST: ${{secrets.DEV_DBR_HOST}}
          # Secure Authentication Token that grants the Databricks CLI permision to make changes in the target Databricks Workspace
          DATABRICKS_TOKEN: ${{secrets.DEV_DBR_TOKEN}}
        # Executes a Terminal command, i.e., "databricks bundle deploy", which reads the "databricks.yml" Configuration file and deploys the Databricks Asset Bundles (DABs) to the specified target environment, i.e., dev
        run: |
          databricks bundle deploy -t dev
